version: "3.7"
services:
  node:
    build: docker/node
    working_dir: /app
    entrypoint: npx http-server -p 8080 public
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/status || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 3s
    ports:
      - 8080:8080
    volumes:
      - .:/app

  circleci:
    image: circleci/circleci-cli:0.1.5691-alpine
    working_dir: /app
    volumes:
      - .:/app
